name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: "ubuntu-20.04"
            python-version: "3.6"
    uses: ./.github/workflows/tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}

  tests-indy:
    name: Tests (Indy)
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: "ubuntu-20.04"
            python-version: "3.6"

    uses: ./.github/workflows/tests-indy.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      indy-version: "1.16.0"
